# Generated by Django 3.0.5 on 2020-06-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='plcaeholder.jpg', upload_to='img'),
            preserve_default=False,
        ),
    ]
